/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BranchesIdRouteImport } from './routes/branches.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIdRoute = BranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/branches/$id': typeof BranchesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/me/': typeof MeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/branches/$id': typeof BranchesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
  '/branches': typeof BranchesIndexRoute
  '/items': typeof ItemsIndexRoute
  '/me': typeof MeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/branches/$id': typeof BranchesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/me/': typeof MeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribute'
    | '/login'
    | '/setup'
    | '/admin/claims'
    | '/admin/settings'
    | '/branches/$id'
    | '/invite/$token'
    | '/items/$id'
    | '/branches/'
    | '/items/'
    | '/me/'
    | '/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribute'
    | '/login'
    | '/setup'
    | '/admin/claims'
    | '/admin/settings'
    | '/branches/$id'
    | '/invite/$token'
    | '/items/$id'
    | '/branches'
    | '/items'
    | '/me'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/contribute'
    | '/login'
    | '/setup'
    | '/admin/claims'
    | '/admin/settings'
    | '/branches/$id'
    | '/invite/$token'
    | '/items/$id'
    | '/branches/'
    | '/items/'
    | '/me/'
    | '/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributeRoute: typeof ContributeRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BranchesIdRoute: typeof BranchesIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ItemsIdRoute: typeof ItemsIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$id': {
      id: '/branches/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof BranchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributeRoute: ContributeRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BranchesIdRoute: BranchesIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  ItemsIdRoute: ItemsIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  MeIndexRoute: MeIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
